### ISSUE TITLE
Konami code breaks icons

### ISSUE THREAD

**Issue by Haroenv** [bullgit/bullgit.github.io#18]
https://github.com/bullgit/bullgit.github.io/pull/16

fix:

```js
Array.prototype.forEach.call(socialicons, function (icon) {
  icon.setAttribute('style', 'font-family: Genericons !important');
});
```

in the `loadcss` function

**Comment by dervondenbergen** [comment]
it is probably better outside of the loadcss function, but it should be called at the same time

**Comment by Haroenv** [comment]
fix: https://github.com/bullgit/bullgit.github.io/pull/20

**Comment by LukyVj** [comment]
So, there is a konami code on bullg.it ?

**Comment by LukyVj** [comment]
Ok, Just tried, it's awesome, BUT IT LACKS OF AWESOMENESS, Lez add Awkwardize : https://github.com/bullgit/awkwardize.css & replace the blue bullgit by the yellow 1999 ( ![](https://demont.is/c/?c=FFF000&w=500&h=200) )

**Comment by Haroenv** [comment]
well, nothing stops you from loading even more stylesheets

**Comment by reimersjan** [comment]
the brutal performance police will stop you :smile:
