### ISSUE TITLE
Use piwik instead of ga

### ISSUE THREAD

**Issue by dervondenbergen** [bullgit/bullgit.github.io#21]
I would prefer the use of [PIWIK](http://piwik.org/) instead of Google Analytics.

For Google Analytics is only one user (I think @reimersjan) but no one else has insights on how the site is frequented.

[UNICOOD.ES](http://unicood.es/) also uses now Google Analytics (https://github.com/bullgit/unicood.es/commit/981498f1b6f5a662e88ababf2f5cc6251eb72441), which is probbaly @LukyVj account.

Setting up a PIWIK installation isn't complicated at all, and all gitches could see the data.

**Comment by LukyVj** [comment]
I'm for it! 

I'll set it up tonite ! :smile:

**Comment by dervondenbergen** [comment]
We would have to migrate the Google Analytics Data before using Piwik

**Comment by LukyVj** [comment]
That must be the longest part ?

**Comment by reimersjan** [comment]
I'm **100% PRO Piwik**. I don't like GA at all. I think we didn't use it back then, because it was complicated to deploy in the pre-uberspace-era

@dervondenbergen there are a a bunch of us who have access to our Ganalytics

**Comment by dervondenbergen** [comment]
not me :(

but i'm setting piwik up right the moment i write this

**Comment by reimersjan** [comment]
@dervondenbergen you now have full access to our GA

**Comment by dervondenbergen** [comment]
I recommend to all to add the piwik cookie, so our own views won't get tracked, only from other people.

**Comment by dervondenbergen** [comment]
I'm talking about our piwik installation. It is reachable at analytics.bullg.it and the login codes are in the shared Google spreadsheet. I would also recommend to add a new user, so everybody could customize the data representation the way he/she wants to.

**Comment by LukyVj** [comment]
@dervondenbergen Where is dat :cookie: ?

**Comment by dervondenbergen** [comment]
@LukyVj http://analytics.bullg.it/index.php?module=UsersManager&action=userSettings&period=day&date=yesterday#/excludeCookie <http://analytics.bullg.it/index.php?module=UsersManager&action=userSettings&period=day&date=yesterday#/excludeCookie>

**Comment by LukyVj** [comment]
If I take this as a proof : https://github.com/bullgit/bullgit.github.io/commit/8809d4c5c182d3fab8388288dd1fff61ab70f7dd 

I think I can close this issue.
