### ISSUE TITLE
implementation of flexbox is broken on Safari

### ISSUE THREAD

**Issue by Haroenv** [bullgit/bullgit.github.io#26]
genericons don't line up as they should, padding seems not to apply and centering is off

![](https://i.imgur.com/KW3J0Yc.png)

**Comment by Haroenv** [comment]
Fixed in Safari 9.0

**Comment by dervondenbergen** [comment]
so just wait for osx 10.11 and safari 9.0 so that the bug is already fixed ?

**Comment by Haroenv** [comment]
Yep, that's what I meant by that comment. So this issue is basically solved

**Comment by dervondenbergen** [comment]
as it is *fixed*, I feel free to close it
