### ISSUE TITLE
all personal websites are linked using http

### ISSUE THREAD

**Issue by Haroenv** [bullgit/bullgit.github.io#35]

**Comment by LukyVj** [comment]
And we have to use `https`  ?

**Comment by Haroenv** [comment]
We don't have to, it's better to if that site has https, but if it doesn't then it won't load.

**Comment by dervondenbergen** [comment]
How would you do that, change the template? @Haroenv

**Comment by Haroenv** [comment]
I guess that would be the only option, or it would be up to all of us setting up a http to https redirect on our personal sites, I haven't yet found out how to do that.

**Comment by dervondenbergen** [comment]
I think it would be better, if we add the protocol to all personal website urls in the members.yaml file, and we get rid of the protocol in the template. That way the People with https have an https link, and those who don't use https have the http link like before

**Comment by Haroenv** [comment]
Or we just add a full address in the `yaml` and then you can manually change it to `https` or `http`, whatever works

**Comment by dervondenbergen** [comment]
Yes, I think we mean the same thing :smile:

**Comment by dervondenbergen** [comment]
Are you making the changes?
