### ISSUE TITLE
Search bar

### ISSUE THREAD

**Issue by JohJakob** [bullgit/bullgit.github.io#58]
A search bar to search for repositories directly on [bullg.it](https://bullg.it) would be great.

**Comment by LukyVj** [comment]
Haha I was assigned because of my position at Algolia :D ?

**Comment by LukyVj** [comment]
But I'm totally up for it 
Just have to make a CRON task to fetch all the new repos 
Or we go with a slow selfmade system.

**Comment by JohJakob** [comment]
@LukyVj Exactly…

**Comment by Haroenv** [comment]
for a simple example how to make it without algolia, for almost the same idea, I made this: https://ikdoeict-notes.github.io

**Comment by Haroenv** [comment]
my example is this:

```
/**
 * Scripts for ikdoeict-notes.github.io
 * MIT
 * @author Haroen Viaene <hello@haroen.me>
 */

window.addEventListener('DOMContentLoaded',function(){
  var search = document.querySelector('.search input');
  var courseNames = document.querySelectorAll('.repos--list h2 a');
  var courseDescriptions = document.querySelectorAll('.repos--list p.main');

  search.addEventListener('input',function(){
    for (var i = 0; i < courseNames.length; i++) {
      if (courseNames[i].innerHTML.toLowerCase().indexOf(search.value.toLowerCase()) === -1 && courseDescriptions[i].innerHTML.toLowerCase().indexOf(search.value.toLowerCase()) === -1) {
        courseNames[i].parentNode.parentNode.classList.add('hidden');
      } else {
        courseNames[i].parentNode.parentNode.classList.remove('hidden');
      }
    };
  });
});
```

just add a css rule for: 

```
.hidden {
display: none;
}
```

and change the classes to ones applicable here.

**Comment by JohJakob** [comment]
@Haroenv Thank you! This looks good. I'll take a look at it as soon as possible.
@LukyVj Maybe the event ```DOMContentLoaded``` works for gitShare.

**Comment by LukyVj** [comment]
I still prefer Algolia 😜😎

**Comment by Haroenv** [comment]
Nothing wrong with keeping it simple until you have time to make it faster @LukyVj 

ship fast

**Comment by LukyVj** [comment]
But where are you doing you http request to the github page @haroenv ?

**Comment by Haroenv** [comment]
it's on the github page?
