### ISSUE TITLE
empty stale branches

### ISSUE THREAD

**Issue by Haroenv** [bullgit/bullgit.github.io#61]
* [dev](https://github.com/bullgit/bullgit.github.io/tree/dev) by @kevingimbel 
* [newRepoList](https://github.com/bullgit/bullgit.github.io/tree/newRepoList) by @kevingimbel 
* [v1](https://github.com/bullgit/bullgit.github.io/tree/v1) by @LukyVj 

These look like they can be deleted

**Comment by kevingimbel** [comment]
Mine can be deleted. If you've time do it, otherwise I'll do it later today!

**Comment by LukyVj** [comment]
Mine too :)
