### ISSUE TITLE
Gitch counter is not working

### ISSUE THREAD

**Issue by JohJakob** [bullgit/bullgit.github.io#80]
The counter in the members section shows "0 Gitches, and counting..".

**Comment by Haroenv** [comment]
Uh oh!!!

**Comment by dervondenbergen** [comment]
This shouldn't be like this, see https://github.com/bullgit/bullgit.github.io/commit/d346cd9fb48a9739cacc895887e923f12668a33d

This seems to be a Jekyll error

**Comment by dervondenbergen** [comment]
loooooool, this is a different counter, why did we have 2 counter :O

**Comment by Haroenv** [comment]
lol, weirdo
